/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_brunopacheco1_qengine_QRuleEngine */

#ifndef _Included_com_github_brunopacheco1_qengine_QRuleEngine
#define _Included_com_github_brunopacheco1_qengine_QRuleEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_brunopacheco1_qengine_QRuleEngine
 * Method:    runCircuit
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_brunopacheco1_qengine_QRuleEngine_runCircuit
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
