/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.brunopacheco1.qengine;

public class qengine {
  public static double run_circuit(long qbit) {
    return qengineJNI.run_circuit(qbit);
  }

}
